# NumPy Quickstart 

We will use the **NumPy** module to create and apply mathematical operations on matrices.

In [71]:
import numpy as np

Create a simple array of integers

In [72]:
array_1d = np.arange(0, 10)

The function `arange` creates an array from `range(0,10)`. The `arange()` function is similar to that of Python's `range()`.

In [73]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a $2\times2$ matrix. (2-dimensional array)

In [74]:
array_2d = np.array([[1, 2], [3, 4]])

In [75]:
array_2d

array([[1, 2],
       [3, 4]])

Create a $3\times 3$ matrix.

In [76]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [77]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two $3\times 3$ matrices.

In [78]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [79]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two $3\times 3$ matrices.

In [80]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [81]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrices.

Remember the rule that the matrix product of a matrix $A$ of shape $m \times n$ with a matrix $B$ of shape $n \times o$ has shape $m \times o$. 

In [82]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [83]:
matrixB = np.array([[1, 1], [1, 1], [1, 1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [84]:
print(np.matmul(matrixA, matrixB))

[[3 3]
 [3 3]
 [3 3]]


The dot product of a $3\times 3$ matrix with a $3\times 2$ matric is a $3\times 2$ matrix.

Generate a $3\times 3$ matrix with all zeros.

In [15]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a $3\times 3$ matrix with all ones.

In [16]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3D tensor.

In [17]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [18]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is described as **Width * Rows * Columns**.

## Common functions to operate on NumPy arrays

In [20]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of the array `array_3x3`.

In [21]:
array_3x3.shape

(3, 3)

Flatten `array_3x3`. Flatten will reduce any array of any dimensions into a 1-dimension array.

In [22]:
flattened_arr = array_3x3.ravel()

In [23]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
flattened_arr.shape

(9,)

**Use the `.copy()` method to clone the matrix instead of doing a reference.**


In [25]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`matrixB` is a reference to `matrixA`.`matrixC` is a copy of `matrixA`.

In [26]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matrixC = np.copy(matrixA)

In [28]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matrixA[0] = [99, 99, 99]

In [30]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [32]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that when we modify `matrixA`, `matrixB` changes, but not `matrixC`

## Array Manipulation

**Perform vertical stack for 2 matrices using `numpy.vstack`.**

In [33]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using `numpy.hstack`.**

In [37]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [38]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using `numpy.dstack`.**

In [39]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrixB = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [40]:
dstack_matrix = np.dstack((matrixA, matrixB))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [41]:
dstack_matrix.shape

(3, 3, 2)

**Transpose a matrix.**

In [42]:
matrixC = np.transpose(matrixA)
matrixC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [43]:
matrixC = matrixA.reshape(1, 9)
matrixC

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at the n-th index to 2 equal-sized subarrays.**

In [44]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
matrixC = np.vsplit(matrixA, 2)
matrixC

[array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally into 3 equal-sized subarrays.** 

In [46]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]),
 array([[0],
        [0],
        [1],
        [1]]),
 array([[0],
        [0],
        [1],
        [1]])]

## Exercise

Create a $5\times 3$ matrix populated with random samples from a uniform distribution and name it **`mat_1`**.

*hint: `numpy.random.rand`*

In [48]:
mat_1 = np.random.rand(5, 3)
mat_1

array([[0.64948872, 0.9447472 , 0.32158808],
       [0.03448921, 0.41154731, 0.37363412],
       [0.28407355, 0.80234352, 0.3967717 ],
       [0.7913013 , 0.46943649, 0.82445257],
       [0.95160864, 0.38866463, 0.01969337]])

Create a matrix **`mat_2`** of any size. The matrix should be eligible to perform matrix multiplication with `mat_1`.

In [49]:
mat_2 = np.random.rand(3, 2)
mat_2

array([[0.28484523, 0.44709315],
       [0.29690407, 0.84910912],
       [0.66881169, 0.35827766]])

Perform matrix multiplication of `mat_1` and `mat_2` and store it in variable **`mat_3`**.

In [50]:
mat_3 = np.matmul(mat_1, mat_2)
mat_3

array([[0.68058492, 1.20779324],
       [0.38190502, 0.49873322],
       [0.58450161, 0.95043897],
       [0.91617952, 1.04777113],
       [0.39962845, 0.76253208]])

Create another matrix that has the same number of columns as `mat_3` and name it **`mat_4`**

In [51]:
mat_4 = np.random.rand(3, 2)
mat_4

array([[0.84772351, 0.91691295],
       [0.64898018, 0.8177684 ],
       [0.62405171, 0.06999039]])

Stack matrix `mat_3` and `mat_4` vertically. Name the result **`mat_5`**.

In [52]:
mat_5 = np.vstack((mat_3, mat_4))
mat_5

array([[0.68058492, 1.20779324],
       [0.38190502, 0.49873322],
       [0.58450161, 0.95043897],
       [0.91617952, 1.04777113],
       [0.39962845, 0.76253208],
       [0.84772351, 0.91691295],
       [0.64898018, 0.8177684 ],
       [0.62405171, 0.06999039]])

Transpose `mat_5` and name the transposed matrix **`mat_6`**.

In [53]:
mat_6 = np.transpose(mat_5)
mat_6

array([[0.68058492, 0.38190502, 0.58450161, 0.91617952, 0.39962845,
        0.84772351, 0.64898018, 0.62405171],
       [1.20779324, 0.49873322, 0.95043897, 1.04777113, 0.76253208,
        0.91691295, 0.8177684 , 0.06999039]])

Check the shape of **`mat_6`**.

In [54]:
mat_6.shape

(2, 8)

Vertically split **`mat_6`** into two subarrays.

In [114]:
arr = np.vsplit(mat_6,2)
arr

[array([[0.68058492, 0.38190502, 0.58450161, 0.91617952, 0.39962845,
         0.84772351, 0.64898018, 0.62405171]]),
 array([[1.20779324, 0.49873322, 0.95043897, 1.04777113, 0.76253208,
         0.91691295, 0.8177684 , 0.06999039]])]

In [115]:
np.hsplit(mat_6,4)

[array([[0.68058492, 0.38190502],
        [1.20779324, 0.49873322]]),
 array([[0.58450161, 0.91617952],
        [0.95043897, 1.04777113]]),
 array([[0.39962845, 0.84772351],
        [0.76253208, 0.91691295]]),
 array([[0.64898018, 0.62405171],
        [0.8177684 , 0.06999039]])]