# NumPy Quickstart 

We will use the **Numpy** module to create and apply mathematical operations on matrices.

In [1]:
import numpy as np

Create a simple array of integers

In [2]:
array_1d = np.arange(0, 10)

In [3]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2x2 matrix.

In [4]:
array_2d = np.array([[1, 2], [3, 4]])

In [5]:
array_2d

array([[1, 2],
       [3, 4]])

Create a 3x3 matrix.

In [6]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two 3x3 matrices.

In [8]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [9]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two 3x3 matrices.

In [10]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [11]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrics.

Following the rule:

M x N * N x O = M x O  matrix

In [12]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
matrixB = np.array([[1, 1], [1, 1], [1, 1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
print(np.matmul(matrixA, matrixB))

[[3 3]
 [3 3]
 [3 3]]


Dot product of 3x3 matrix  with 2x2 matric is a 3x2 matrix.

Generate a 3x3 matrix with all zeros.

In [15]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a 3x3 matrix with all ones.

In [16]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3d tensor.

In [17]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [18]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is describe as **Width * Rows * Columns**.

# Common functions to operate on NumPy arrays

In [20]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of array.

In [21]:
array_3x3.shape

(3, 3)

Flatten an array

In [22]:
flattened_arr = array_3x3.ravel()

In [23]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
flattened_arr.shape

(9,)

**Use copy() to clone the matrix instead of doing a reference.**

In [25]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

MatrixB is a reference to MatrixA. MatrixC is a copy of MatrixA.

In [26]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matrixC = np.copy(matrixA)

In [28]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matrixA[0] = [99, 99, 99]

In [30]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [32]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that, when we modify MatrixA, MatrixB changes, but not MatrixC.

# Array Manipulation

**Perform vertical stack for 2 matrices using numpy.vstack.**

In [33]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using numpy.hstack.**

In [37]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [38]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using numpy.dstack.**

In [39]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrixB = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [40]:
dstack_matrix = np.dstack((matrixA, matrixB))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [41]:
dstack_matrix.shape

(3, 3, 2)

**Transpose a matrix.**

In [42]:
matrixC = np.transpose(matrixA)
matrixC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [43]:
matrixC = matrixA.reshape(1, 9)
matrixC

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at n-th index to 2 equal size subarray.**

In [44]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
matrixC = np.vsplit(matrixA, 2)
matrixC

[array([[0, 0, 0],
        [0, 0, 0]]), array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally to 3 equal size subarray.**

In [46]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]])]