# NumPy Quickstart 

We will use the **Numpy** module to create and apply mathematical operations on matrices.

In [2]:
import numpy as np

Create a simple array of integers

In [2]:
array_1d = np.arange(0, 10)

In [3]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2x2 matrix.

In [4]:
array_2d = np.array([[1, 2], [3, 4]])

In [5]:
array_2d

array([[1, 2],
       [3, 4]])

Create a 3x3 matrix.

In [6]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two 3x3 matrices.

In [8]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [9]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two 3x3 matrices.

In [10]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [11]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrics.

Following the rule:

M x N * N x O = M x O  matrix

In [12]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
matrixB = np.array([[1, 1], [1, 1], [1, 1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
print(np.matmul(matrixA, matrixB))

[[3 3]
 [3 3]
 [3 3]]


Dot product of 3x3 matrix  with 2x2 matric is a 3x2 matrix.

Generate a 3x3 matrix with all zeros.

In [15]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a 3x3 matrix with all ones.

In [16]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3d tensor.

In [17]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [18]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is describe as **Width * Rows * Columns**.

# Common functions to operate on NumPy arrays

In [20]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of array.

In [21]:
array_3x3.shape

(3, 3)

Flatten an array

In [22]:
flattened_arr = array_3x3.ravel()

In [23]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
flattened_arr.shape

(9,)

**Use copy() to clone the matrix instead of doing a reference.**

In [25]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

MatrixB is a reference to MatrixA. MatrixC is a copy of MatrixA.

In [26]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matrixC = np.copy(matrixA)

In [28]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matrixA[0] = [99, 99, 99]

In [30]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [32]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that, when we modify MatrixA, MatrixB changes, but not MatrixC.

# Array Manipulation

**Perform vertical stack for 2 matrices using numpy.vstack.**

In [33]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using numpy.hstack.**

In [37]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [38]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using numpy.dstack.**

In [39]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrixB = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [40]:
dstack_matrix = np.dstack((matrixA, matrixB))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [41]:
dstack_matrix.shape

(3, 3, 2)

**Transpose a matrix.**

In [42]:
matrixC = np.transpose(matrixA)
matrixC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [43]:
matrixC = matrixA.reshape(1, 9)
matrixC

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at n-th index to 2 equal size subarray.**

In [44]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
matrixC = np.vsplit(matrixA, 2)
matrixC

[array([[0, 0, 0],
        [0, 0, 0]]), array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally to 3 equal size subarray.**

matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

In [47]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]])]

# Exercise

Create a 5x3 matrix populate with random samples from a uniform distribution and named it **mat_1**

*hint: numpy.random.rand*

In [11]:
mat_1 = np.random.rand(5,3)
mat_1

array([[0.79359584, 0.81437835, 0.48631452],
       [0.58610499, 0.8527377 , 0.05283724],
       [0.24931228, 0.59145682, 0.24867077],
       [0.47429356, 0.65154835, 0.7993395 ],
       [0.00874279, 0.24418112, 0.84156251]])

Create any size of matrix, the matrix should be eligible to perform matrix multiplication with mat_1 and named it **mat_2**

In [16]:
mat_2 = np.random.rand(3, 2)
mat_2

array([[0.07961098, 0.70429713],
       [0.58175453, 0.16832679],
       [0.19551477, 0.15731854]])

Perform matrix multiplication of mat_1 and mat_2 and store it in variable **mat_3**

In [15]:
mat_3 = np.matmul(mat_1, mat_2)
mat_3

array([[0.5581948 , 0.53964074],
       [0.17208147, 0.42525575],
       [0.28963496, 0.32584903],
       [0.78736716, 0.50956363],
       [0.74868255, 0.29920713]])

Create another matrix that has the column size similar with mat_3 and named it **mat_4**

In [21]:
mat_4 = np.random.rand(3,2)
mat_4

array([[0.27058377, 0.26278956],
       [0.5697448 , 0.31804932],
       [0.84315007, 0.6911341 ]])

Stack matrix mat_3 and mat_4 vertically and named it **mat_5**

In [20]:
mat_5 = np.vstack((mat_3, mat_4))
mat_5

array([[0.5581948 , 0.53964074],
       [0.17208147, 0.42525575],
       [0.28963496, 0.32584903],
       [0.78736716, 0.50956363],
       [0.74868255, 0.29920713],
       [0.96191497, 0.19868666],
       [0.09789717, 0.26911424],
       [0.42049912, 0.29332739]])

Perform transpose on mat_5 and named it **mat_6**


In [23]:
mat_6 = np.transpose(mat_5)
mat_6

array([[0.5581948 , 0.17208147, 0.28963496, 0.78736716, 0.74868255,
        0.96191497, 0.09789717, 0.42049912],
       [0.53964074, 0.42525575, 0.32584903, 0.50956363, 0.29920713,
        0.19868666, 0.26911424, 0.29332739]])

Check the shape of **mat_6**


In [24]:
mat_6.shape

(2, 8)