# NumPy Quickstart 

We will use the **NumPy** module to create and apply mathematical operations on matrices.

In [1]:
import numpy as np

Create a simple array of integers

In [2]:
array_1d = np.arange(0, 10)

In [3]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2x2 matrix.

In [4]:
array_2d = np.array([[1, 2], [3, 4]])

In [5]:
array_2d

array([[1, 2],
       [3, 4]])

Create a $3\times 3$ matrix.

In [6]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two $3\times 3$ matrices.

In [8]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [9]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two $3\times 3$ matrices.

In [10]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [11]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrices.

Remember the rule that the matrix product of a matrix $A$ of shape $m \times n$ with a matrix $B$ of shape $n \times o$ has shape $m \times o$. 

In [12]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
matrixB = np.array([[1, 1], [1, 1], [1, 1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
print(np.matmul(matrixA, matrixB))

[[3 3]
 [3 3]
 [3 3]]


The dot product of a $3\times 3$ matrix with a $3\times 2$ matric is a $3\times 2$ matrix.

Generate a $3\times 3$ matrix with all zeros.

In [15]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a $3\times 3$ matrix with all ones.

In [16]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3D tensor.

In [17]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [18]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is described as **Width * Rows * Columns**.

## Common functions to operate on NumPy arrays

In [20]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of the array `array_3x3`.

In [21]:
array_3x3.shape

(3, 3)

Flatten `array_3x3`.

In [22]:
flattened_arr = array_3x3.ravel()

In [23]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
flattened_arr.shape

(9,)

**Use the `.copy()` method to clone the matrix instead of doing a reference.**

In [25]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`matrixB` is a reference to `matrixA`. `matrixC` is a copy of `matrixA`.

In [26]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matrixC = np.copy(matrixA)

In [28]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matrixA[0] = [99, 99, 99]

In [30]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [32]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that when we modify `matrixA`, `matrixB` changes, but not `matrixC`.

## Array Manipulation

**Perform vertical stack for 2 matrices using `numpy.vstack`.**

In [33]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using `numpy.hstack`.**

In [37]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [38]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using `numpy.dstack`.**

In [39]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrixB = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [40]:
dstack_matrix = np.dstack((matrixA, matrixB))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [41]:
dstack_matrix.shape

(3, 3, 2)

**Transpose a matrix.**

In [42]:
matrixC = np.transpose(matrixA)
matrixC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [43]:
matrixC = matrixA.reshape(1, 9)
matrixC

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at the n-th index to 2 equal-sized subarrays.**

In [44]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
matrixC = np.vsplit(matrixA, 2)
matrixC

[array([[0, 0, 0],
        [0, 0, 0]]), array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally into 3 equal-sized subarrays.**

In [46]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]])]

## Exercise

Create a $5\times 3$ matrix populated with random samples from a uniform distribution and name it **`mat_1`**.

*hint: `numpy.random.rand`*

In [48]:
mat_1 = np.random.rand(5, 3)
mat_1

array([[9.42322372e-01, 4.95904570e-01, 4.05094129e-01],
       [2.77822909e-01, 7.80287702e-02, 8.30922277e-02],
       [1.71710336e-01, 2.20628399e-01, 8.93545212e-02],
       [3.16932477e-01, 8.67414073e-01, 9.59836767e-01],
       [2.58600630e-01, 6.34966749e-01, 1.03448541e-05]])

Create a matrix **`mat_2`** of any size. The matrix should be eligible to perform matrix multiplication with `mat_1`.

In [49]:
mat_2 = np.random.rand(3, 2)
mat_2

array([[0.34717497, 0.19215718],
       [0.92522523, 0.16858722],
       [0.6694117 , 0.53107251]])

Perform matrix multiplication of `mat_1` and `mat_2` and store it in variable **`mat_3`**.

In [50]:
mat_3 = np.matmul(mat_1, mat_2)
mat_3

array([[1.05714891, 0.47981154],
       [0.22427026, 0.11066832],
       [0.32355945, 0.11764423],
       [1.55511037, 0.71687871],
       [0.67727385, 0.15674474]])

Create another matrix that has the same number of columns as `mat_3` and name it **`mat_4`**

In [51]:
mat_4 = np.random.rand(3, 2)
mat_4

array([[0.28454642, 0.463742  ],
       [0.39571117, 0.39231936],
       [0.10052996, 0.76686513]])

Stack matrix `mat_3` and `mat_4` vertically. Name the result **mat_5**.

In [52]:
mat_5 = np.vstack((mat_3, mat_4))
mat_5

array([[1.05714891, 0.47981154],
       [0.22427026, 0.11066832],
       [0.32355945, 0.11764423],
       [1.55511037, 0.71687871],
       [0.67727385, 0.15674474],
       [0.28454642, 0.463742  ],
       [0.39571117, 0.39231936],
       [0.10052996, 0.76686513]])

Transpose `mat_5` and name the transposed matrix **`mat_6`**.

In [53]:
mat_6 = np.transpose(mat_5)
mat_6

array([[1.05714891, 0.22427026, 0.32355945, 1.55511037, 0.67727385,
        0.28454642, 0.39571117, 0.10052996],
       [0.47981154, 0.11066832, 0.11764423, 0.71687871, 0.15674474,
        0.463742  , 0.39231936, 0.76686513]])

Check the shape of **`mat_6`**.

In [54]:
mat_6.shape

(2, 8)