# Perform Classification by using K Nearest Neighbour (KNN)

In [2]:
import numpy as np
from sklearn import datasets
from sklearn import model_selection
from sklearn import metrics

import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
iris = datasets.load_iris()

In [7]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [8]:
iris.data.shape

(150, 4)

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
data = iris.data.astype(np.float32)
target = iris.target.astype(np.float32)

In [12]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(
    data, target, test_size=0.3, random_state=123
)

In [13]:
X_train.shape, y_train.shape

((105, 4), (105,))

In [14]:
X_test.shape, y_test.shape

((45, 4), (45,))

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
model = KNeighborsClassifier(n_neighbors =3)

In [17]:
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [18]:
predictions=model.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predictions))

[[18  0  0]
 [ 0  9  1]
 [ 0  1 16]]


In [20]:
metrics.accuracy_score(y_test, predictions)

0.9555555555555556