In [1]:
# Copyright (c) 2020-2021 CertifAI Sdn. Bhd.
# 
# This program is part of OSRFramework. You can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# NumPy Quickstart 

We will use the **NumPy** module to create and apply mathematical operations on matrices.

In [2]:
import numpy as np

Create a simple array of integers

In [3]:
array_1d = np.arange(0, 10)

The function `arange` creates an array from `range(0,10)`. The `arange()` function is similar to that of Python's `range()`.

In [4]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a $2\times2$ matrix. (2-dimensional array)

In [5]:
array_2d = np.array([[1, 2], [3, 4]])

In [6]:
array_2d

array([[1, 2],
       [3, 4]])

Create a $3\times 3$ matrix.

In [7]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two $3\times 3$ matrices.

In [9]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [10]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two $3\times 3$ matrices.

In [11]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [12]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrices.

Remember the rule that the matrix product of a matrix $A$ of shape $m \times n$ with a matrix $B$ of shape $n \times o$ has shape $m \times o$. 

In [13]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
matrixB = np.array([[1, 1], [1, 1], [1, 1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
print(np.matmul(matrixA, matrixB))

[[3 3]
 [3 3]
 [3 3]]


The dot product of a $3\times 3$ matrix with a $3\times 2$ matric is a $3\times 2$ matrix.

Generate a $3\times 3$ matrix with all zeros.

In [16]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a $3\times 3$ matrix with all ones.

In [17]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3D tensor.

In [18]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [19]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is described as **Width * Rows * Columns**.

Below is an example of a 4-dimension tensor, or a tensor of `rank 4`.

In [21]:
tensor_4 = np.array([[[[1,2,3,7],
                       [1,3,5,0],
                       [2,3,4,4]],
                      [[2,3,4,6],
                       [6,3,4,8],
                       [4,6,0,7]]],
                     [[[1,2,6,9],
                       [2,3,4,3],
                       [7,4,4,3]],
                      [[2,6,4,3],
                       [7,3,4,2],
                       [8,5,6,8]]]])

Using the `shape` attribute, we can see the magnitude of dimensions of said tensor.<br><br>
A $n$-dimension tensor will display a number of $n$ magnitudes. We can also use `ndim` to show the rank(dimension) of the tensor.

In [22]:
print(tensor_4.shape)
print(tensor_4.ndim)

(2, 2, 3, 4)
4


## Common functions to operate on NumPy arrays

In [23]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of the array `array_3x3`.

In [24]:
array_3x3.shape

(3, 3)

Flatten `array_3x3`. Flatten will reduce any array of any dimensions into a 1-dimension array.

In [25]:
flattened_arr = array_3x3.ravel()

In [26]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
flattened_arr.shape

(9,)

**Use the `.copy()` method to clone the matrix instead of doing a reference.**


In [28]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`matrixB` is a reference to `matrixA`.`matrixC` is a copy of `matrixA`.

In [29]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matrixC = np.copy(matrixA)

In [31]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
matrixA[0] = [99, 99, 99]

In [33]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [34]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that when we modify `matrixA`, `matrixB` changes, but not `matrixC`

## Array Manipulation

**Perform vertical stack for 2 matrices using `numpy.vstack`.**

In [36]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using `numpy.hstack`.**

In [40]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [41]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using `numpy.dstack`.**

In [42]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrixB = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [43]:
dstack_matrix = np.dstack((matrixA, matrixB))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [44]:
dstack_matrix.shape

(3, 3, 2)

**Transpose a matrix.**

In [45]:
matrixC = np.transpose(matrixA)
matrixC

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [46]:
matrixC = matrixA.reshape(1, 9)
matrixC

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at the n-th index to 2 equal-sized subarrays.**

In [47]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [48]:
matrixC = np.vsplit(matrixA, 2)
matrixC

[array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally into 3 equal-sized subarrays.** 

In [49]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]),
 array([[0],
        [0],
        [1],
        [1]]),
 array([[0],
        [0],
        [1],
        [1]])]

## Exercise

Create a $5\times 3$ matrix populated with random samples from a uniform distribution and name it **`mat_1`**.

*hint: `numpy.random.rand`*

In [51]:
mat_1 = np.random.rand(5, 3)
mat_1

array([[0.11966087, 0.47748488, 0.15096113],
       [0.1030203 , 0.45308454, 0.24235349],
       [0.39663288, 0.06131643, 0.36671067],
       [0.280654  , 0.30957119, 0.56012112],
       [0.02133816, 0.60018283, 0.24385118]])

Create a matrix **`mat_2`** of any size. The matrix should be eligible to perform matrix multiplication with `mat_1`.

In [52]:
mat_2 = np.random.rand(3, 2)
mat_2

array([[0.37008906, 0.97976583],
       [0.52495173, 0.69590459],
       [0.32629952, 0.66861873]])

Perform matrix multiplication of `mat_1` and `mat_2` and store it in variable **`mat_3`**.

In [53]:
mat_3 = np.matmul(mat_1, mat_2)
mat_3

array([[0.34420024, 0.55045899],
       [0.35505402, 0.57828146],
       [0.29863517, 0.67646735],
       [0.44914417, 0.86491469],
       [0.40253256, 0.60161985]])

Create another matrix that has the same number of columns as `mat_3` and name it **`mat_4`**

In [54]:
mat_4 = np.random.rand(3, 2)
mat_4

array([[0.60797561, 0.71906173],
       [0.89204501, 0.14677977],
       [0.46133693, 0.53957826]])

Stack matrix `mat_3` and `mat_4` vertically. Name the result **`mat_5`**.

In [55]:
mat_5 = np.vstack((mat_3, mat_4))
mat_5

array([[0.34420024, 0.55045899],
       [0.35505402, 0.57828146],
       [0.29863517, 0.67646735],
       [0.44914417, 0.86491469],
       [0.40253256, 0.60161985],
       [0.60797561, 0.71906173],
       [0.89204501, 0.14677977],
       [0.46133693, 0.53957826]])

Transpose `mat_5` and name the transposed matrix **`mat_6`**.

In [56]:
mat_6 = np.transpose(mat_5)
mat_6

array([[0.34420024, 0.35505402, 0.29863517, 0.44914417, 0.40253256,
        0.60797561, 0.89204501, 0.46133693],
       [0.55045899, 0.57828146, 0.67646735, 0.86491469, 0.60161985,
        0.71906173, 0.14677977, 0.53957826]])

Check the shape of **`mat_6`**.

In [57]:
mat_6.shape

(2, 8)

Vertically split **`mat_6`** into two subarrays.

In [58]:
arr = np.vsplit(mat_6,2)
arr

[array([[0.34420024, 0.35505402, 0.29863517, 0.44914417, 0.40253256,
         0.60797561, 0.89204501, 0.46133693]]),
 array([[0.55045899, 0.57828146, 0.67646735, 0.86491469, 0.60161985,
         0.71906173, 0.14677977, 0.53957826]])]