# Matrices and Linear Algebra

We will use the **Numpy** module to create matrices and apply mathematical operations.

In [1]:
import numpy as np

Create a simple array of integers

In [2]:
array_1d = np.arange(0,10)

In [3]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2x2 matrix.

In [4]:
array_2d = np.array([[1,2],[3,4]])

In [5]:
array_2d

array([[1, 2],
       [3, 4]])

Create a 3x3 matrix.

In [6]:
array_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two 3x3 matrices.

In [8]:
matrixA = np.array([[1,1,1],[1,1,1],[1,1,1]])
matrixB = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [9]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two 3x3 matrices.

In [10]:
matrixA = np.array([[2,2,2],[2,2,2],[2,2,2]])
matrixB = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [11]:
print(np.subtract(matrixA,matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrics.

Following the rule:

M x N * N x O = M x O  matrix

In [12]:
matrixA = np.array([[1,1,1],[1,1,1],[1,1,1]])
matrixA

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
matrixB = np.array([[1,1],[1,1],[1,1]])
matrixB

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
print(np.dot(matrixA,matrixB))

[[3 3]
 [3 3]
 [3 3]]


Dot product of 3x3 matrix  with 2x2 matric is a 3x2 matrix.

Generate a 3x3 matrix with all zeros.

In [15]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a 3x3 matrix with all ones.

In [17]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3d tensor.

In [18]:
tensor_3d=np.array([[[1,1,1,1],
                     [1,1,1,1],
                     [1,1,1,1]],
                    
                    [[1,1,1,1],
                     [1,1,1,1],
                     [1,1,1,1]]
                   ])

In [19]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is describe as **Width * Rows * Columns**.

# Common functions to operate on a numpy arrays

In [22]:
array_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of array.

In [23]:
array_3x3.shape

(3, 3)

Flatten an array

In [24]:
flattened_arr=array_3x3.ravel()

In [25]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
flattened_arr.shape

(9,)